### ISSUE TITLE
构建docker时报错

### ISSUE THREAD

**Issue by tamakyi** [Xinrea/JoiAsk#1]
运行命令`docker build -t joiask .`
报错如下：
`61 error code ENOENT
62 error syscall open
63 error path /work/package.json
64 error errno -2
65 error enoent ENOENT: no such file or directory, open '/work/package.json'
66 error enoent This is related to npm not being able to find a file.
`

**Comment by Xinrea** [comment]
git clone的时候记得加上--recursive，或者手动clone前端项目到frontend文件夹，docker构建的时候会同时构建打包前端项目的.
