### ISSUE TITLE
修改了默认的账号密码 之后想再修改和再添加用户就会显示权限不足

### ISSUE THREAD

**Issue by 7788u** [Xinrea/JoiAsk#5]
![d01f1f0136f7d8402a467c1124f7547](https://github.com/user-attachments/assets/531388d7-3e36-4a39-bc17-0772db58adc4)
![3d5ef5c427f0b347b770cb5e0bbc7fa](https://github.com/user-attachments/assets/dcdf5445-2d2f-4caa-812e-abe3bd024bec)

试过换浏览器 
和重新登陆/admin 
都是显示权限不足

**Comment by Xinrea** [comment]
管理员账户的用户名 `admin` 应当是固定的（当时简单粗暴这样实现的），在使用时不应修改 admin 的用户名；如果想要其他用户名请直接添加用户。

目前的情况下，如果没有实际数据的话可以直接清空/删除数据库，重启程序自动重新建立初始账号；如果已有数据，可以手动在数据库中将 admins 表内的账号名更改回 admin。

后续会把账号管理这一块修改下，之前实现的太粗糙了 😶

**Comment by 7788u** [comment]
了解了，感谢！！
